name: "Terraform"

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

      aws-assume-role-arn:
        type: string
        required: true

      aws-region:
        type: string
        required: true

      aws-statefile-s3-bucket:
        type: string
        required: true

      aws-lock-dynamo-table:
        type: string
        required: true


jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3  
        with:
          terraform_version: 1.8.3

      - name: Config AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-assume-role-arn }}
          aws-region: us-east-1
          role-session-name: terraform

      - name: Terraform Init
        run: |
          cd infra && terraform init \
          -backend-config="bucket=${{ inputs.aws-statefile-s3-bucket }}" \
          -backend-config="key=${{ github.event.repository.name }}" \
          -backend-config="dynamodb_table=${{ inputs.aws-lock-dynamo-table }}" 

      - name: Terraform Validate
        run: |
          terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          cd infra && 
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform plan -var-file="./ambientes/${{ inputs.environment }}/terraform.tfvars" -out="${{ inputs.environment }}.plan"

      - name: Terraform Apply
        id: apply
        run: |
          cd infra && 
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform apply "${{ inputs.environment }}.plan"
